# Generated by Django 5.1 on 2025-10-31 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tyre_brand_name', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50, unique=True)),
                ('UserOTP', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TyreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.CharField(default='0', max_length=10)),
                ('ratio', models.CharField(default='0', max_length=10)),
                ('rim', models.CharField(default='0', max_length=10)),
                ('tyreType', models.CharField(choices=[('radial', 'Radial'), ('nylon', 'Nylon'), ('notSelected', 'Not Selected')], default='notSelected', max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateDistributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Shop_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobileNo', models.CharField(max_length=10, unique=True)),
                ('otp', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('brands', models.ManyToManyField(blank=True, related_name='distributors', to='apiapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CreateSubUser',
            fields=[
                ('Subuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shop_Name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobileNo', models.CharField(max_length=10)),
                ('discount_percantage', models.FloatField(max_length=5)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers', to='apiapp.createdistributor')),
            ],
        ),
        migrations.CreateModel(
            name='TyrePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='apiapp/images/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='apiapp.brand')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='apiapp.tyremodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
