# Generated by Django 5.1 on 2025-10-06 08:11

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDistributor',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shop_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=10)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DistributorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name=django.contrib.auth.models.User)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TyreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.CharField(default='0', max_length=10)),
                ('ratio', models.CharField(default='0', max_length=10)),
                ('rim', models.CharField(default='0', max_length=10)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateSubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=10)),
                ('discount_percantage', models.FloatField(max_length=5)),
                ('password', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('Distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.createdistributor')),
            ],
        ),
        migrations.CreateModel(
            name='TyrePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='apiapp.tyremodel')),
            ],
        ),
    ]
