# Generated by Django 5.1 on 2025-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdistributor',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
