# Generated by Django 5.1 on 2025-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createsubuser',
            old_name='Distributor',
            new_name='Distributor_Name',
        ),
        migrations.RenameField(
            model_name='createsubuser',
            old_name='username',
            new_name='Shop_Name',
        ),
        migrations.AddField(
            model_name='createsubuser',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tyrepattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apiapp/images/'),
        ),
    ]
