# Generated by Django 5.1 on 2025-10-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_rename_distributor_createsubuser_distributor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createsubuser',
            name='end_date',
        ),
        migrations.AddField(
            model_name='createsubuser',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
