# Generated by Django 5.1 on 2025-11-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_createdistributor_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createsubuser',
            old_name='Subuser_id',
            new_name='id',
        ),
    ]
