# Generated by Django 5.1 on 2025-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_remove_createsubuser_end_date_createsubuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsubuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
