# Generated by Django 5.1 on 2025-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_createsubuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdistributor',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='createdistributor',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
