# Generated by Django 5.1 on 2025-10-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_createdistributor_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdistributor',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='createdistributor',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='createsubuser',
            name='Distributor_Name',
        ),
        migrations.AddField(
            model_name='createsubuser',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers', to='apiapp.createdistributor'),
        ),
        migrations.AddField(
            model_name='distributorlogin',
            name='shop_name',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createsubuser',
            name='Shop_Name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subuserlogin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
