# Generated by Django 5.1 on 2025-10-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_remove_createdistributor_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributorlogin',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='distributorlogin',
            name='otp_created_at',
        ),
        migrations.AddField(
            model_name='createdistributor',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='createdistributor',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorlogin',
            name='UserOTP',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='createdistributor',
            name='mobileNo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='createsubuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
