# Generated by Django 5.1 on 2025-10-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_distributorlogin_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdistributor',
            name='otp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
