# Generated by Django 5.1 on 2025-10-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_createdistributor_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='createsubuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='createdistributor',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='distributors', to='apiapp.brand'),
        ),
        migrations.AddField(
            model_name='tyrepattern',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='apiapp.brand'),
        ),
    ]
