# Generated by Django 5.1 on 2025-10-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_brand_alter_createsubuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createsubuser',
            name='distributor',
        ),
    ]
