# Generated by Django 5.1 on 2025-10-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_remove_createsubuser_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='createsubuser',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subusers', to='apiapp.createdistributor'),
        ),
    ]
