# Generated by Django 5.1 on 2025-10-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_createsubuser_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='code',
            new_name='Tyre_brand_name',
        ),
    ]
