# Generated by Django 5.1 on 2025-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_rename_code_brand_tyre_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdistributor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
